AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an EC2 instance with security group

Resources:
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"             # Allow SSH from anywhere (modify as needed)
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"              # Allow HTTP from anywhere

  HTWInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-00385a401487aefa4"   # Specify the AMI ID for your region
      InstanceType: "t2.micro"             # Specify the instance type


Outputs:
  InstanceId:
    Description: "Instance ID of the newly created EC2 instance"
    Value: !Ref HTWInstance

  PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt HTWInstance.PublicIp
